version: '3.8'
services:
  php-apache-environment:
    image: bany/kuis2
    container_name: php-apache
    depends_on:
      - db
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 8000:80
    networks:
      - backend
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: ajc
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./ajc/docker-entrypoint-initdb.d/ajc.sql
    network:
      -backend

volumes:
  db:

  